name: Netsip CDR Sync

on:
  schedule:
    - cron: "0 */8 * * *" # Every 8 hours
  workflow_dispatch:

jobs:
  fetch-cdrs:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Netsip CDR sync
        run: npx tsx automation/cdr-sync/netsip/index.ts
        env:
          NETSIP_USERNAME: ${{ secrets.NETSIP_USERNAME }}
          NETSIP_PASSWORD: ${{ secrets.NETSIP_PASSWORD }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}

      - name: Commit & push logs (optional)
        shell: powershell
        run: |
          git config --global user.name "netsip-bot"
          git config --global user.email "ci@netsip.local"
          git add logs/*.txt
          if (-not (git diff --cached --quiet)) {
            git commit -m "CDR sync log for $(Get-Date -Format 'yyyy-MM-dd')"
            git push origin master
          } else {
            Write-Host "Nothing to commit"
          }
